# Change these first
owner: DaMnGoodIT # Your GitHub organization or username, where this repository lives
repo: upptime # The name of this repository

sites:
  - name: Matrix - Synapse
    url: https://matrix.b0t.at/health
  - name: b0t.at
    url: https://b0t.at
  - name: Mastodon
    url: https://social.b0t.at
  - name: Privatebin
    url: https://bin.b0t.at

assignees: # Users to assign downtime issues (optional)
  - a-mnich
  - utesgui

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  cname: status.b0t.at
  # baseUrl: /your-repo-name
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: DaMnGoodIT Upptime
  introTitle: "Uptime monitor and status page, powered entirely by GitHub."
  introMessage: This is the DaMnGoodIT / B0t.at Uptime Monitor
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
